# -*- coding: utf-8 -*-
"""Generation Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0B9TrMos7sS7dYdLJBtg7lsfSYV4zlm
"""

pip install torch transformers peft pandas safetensors

import torch
import pandas as pd
import numpy as np
from transformers import T5TokenizerFast, T5ForConditionalGeneration
from peft import PeftModel
from tqdm.auto import tqdm

# --- Helper functions from your training script ---
def parse_row_text(text: str, columns: list) -> dict:
    out = {c: np.nan for c in columns}
    chunks = [p.strip() for p in text.split("|")]
    for part in chunks:
        if ":" not in part: continue
        k, v = part.split(":", 1)
        k = k.strip()
        if k in out: out[k] = v.strip()
    return out

def run_synthetic_generation():
    # 1. Setup Paths and Parameters
    base_model_id = "t5-small"
    adapter_path = "./"  # Path to adapter_model.safetensors and tokenizer

    # List of output files requested
    output_files = [
        "healthcare_dataset_sample1_dp.csv",
        "healthcare_dataset_sample2_dp.csv",
        "healthcare_dataset_sample3_dp.csv"
    ]

    # We need the columns to parse the output correctly.
    columns = [
        "Name", "Age", "Gender", "Blood Type", "Medical Condition",
        "Doctor", "Hospital", "Insurance Provider", "Billing Amount",
        "Room Number", "Admission Type", "Medication", "Test Results"
    ]

    # Generation parameters (matching your training config)
    prompt = "Generate one realistic synthetic patient row:"
    num_rows_to_generate = 1000
    batch_size = 16

    print("Loading tokenizer and base model...")
    tokenizer = T5TokenizerFast.from_pretrained(adapter_path)
    base_model = T5ForConditionalGeneration.from_pretrained(base_model_id)

    print("Loading LoRA adapter weights...")
    model = PeftModel.from_pretrained(base_model, adapter_path)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model.to(device)
    model.eval()

    # Prepare the static prompt for batching
    prompt_batch = [prompt] * batch_size

    # 2. Iterate through each output file and generate Data
    for output_file in output_files:
        print(f"\n--- Generating {num_rows_to_generate} synthetic rows for {output_file} ---")
        generated_texts = []

        for start in tqdm(range(0, num_rows_to_generate, batch_size), desc=f"Generating {output_file}"):
            # Handle the last batch if it's smaller than batch_size
            current_batch_size = min(batch_size, num_rows_to_generate - start)
            current_prompts = prompt_batch[:current_batch_size]

            inputs = tokenizer(
                current_prompts,
                return_tensors="pt",
                padding="max_length",
                truncation=True,
                max_length=64 # matching max_input_len from training
            ).to(device)

            with torch.no_grad():
                outputs = model.generate(
                    input_ids=inputs["input_ids"],
                    attention_mask=inputs["attention_mask"],
                    max_new_tokens=160, # matching max_new_tokens from training
                    do_sample=True,
                    top_p=0.95,
                    temperature=0.9
                )

            decoded_outputs = tokenizer.batch_decode(outputs, skip_special_tokens=True)
            generated_texts.extend(decoded_outputs)

        # 3. Parse generated text back into tabular format
        print(f"\nParsing generated text into tabular format for {output_file}...")
        synth_rows = [parse_row_text(text, columns) for text in generated_texts]
        synth_df = pd.DataFrame(synth_rows, columns=columns)

        # Save Output
        synth_df.to_csv(output_file, index=False)
        print(f"DONE: Generated {len(synth_df)} rows and saved to {output_file}")

if __name__ == "__main__":
    run_synthetic_generation()