# -*- coding: utf-8 -*-
"""Training Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bWKhhmqwvf_ho3CUOVnk5rt47uQndVfD
"""

!pip install -q torch transformers peft opacus pandas numpy tqdm

import math
import random
import time
import warnings
import gc
import shutil
from typing import Dict, List, Optional

import numpy as np
import pandas as pd
import torch
from opacus import PrivacyEngine
from opacus.accountants.utils import get_noise_multiplier
from opacus.utils.batch_memory_manager import BatchMemoryManager
from peft import LoraConfig, TaskType, get_peft_model
from torch.utils.data import DataLoader, Dataset
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from tqdm.auto import tqdm

warnings.filterwarnings("ignore")

# ==========================================
# CONFIGURATION
# ==========================================
CONFIG = {
    "csv_path": "/content/healthcare_dataset.csv",
    "out_csv": "/content/healthcare_dataset_dp.csv",
    "model_name": "t5-small",
    "prompt": "Generate one realistic synthetic patient row:",

    # Training Params
    "target_epsilon": 10.0,
    "delta": 1e-5,
    "epochs": 5,
    "logical_batch_size": 64,
    "physical_batch_size": 16,
    "max_grad_norm": 1.0,
    "lr": 5e-4,

    # Data Params
    "max_input_len": 64,
    "max_target_len": 256,

    # Generation Params
    "n_generate": None,
    "temperature": 0.9,
    "top_p": 0.95,
    "max_new_tokens": 160,
    "seed": 42,

    # ── Saving ──────────────────────────────────────────────────
    "save_every_n_epochs": 1,           # Save a checkpoint every N epochs
    "local_checkpoint_dir": "/content/checkpoints",   # Local checkpoint folder
    "drive_save_dir": "/content/lora_checkpoints",  # Google Drive backup folder
    "save_to_drive": True,              # Set False if you don't want Drive backup
}


# ==========================================
# HELPERS
# ==========================================
def print_gpu_status():
    if torch.cuda.is_available():
        vram_allocated = torch.cuda.memory_allocated() / 1024**3
        vram_reserved = torch.cuda.memory_reserved() / 1024**3
        print(f"   [GPU] {torch.cuda.get_device_name(0)} | Allocated: {vram_allocated:.2f} GB | Reserved: {vram_reserved:.2f} GB")
    else:
        print("   [GPU Status] WARNING: Running on CPU.")

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

def stringify_value(v) -> str:
    if pd.isna(v): return "MISSING"
    if isinstance(v, (float, np.floating)):
        if not np.isfinite(v): return "MISSING"
        return f"{float(v):.6g}"
    return str(v).replace("\n", " ").strip()

def serialize_row(row: pd.Series, columns: List[str]) -> str:
    return " | ".join(f"{c}: {stringify_value(row[c])}" for c in columns)

def parse_row_text(text: str, columns: List[str]) -> Dict[str, str]:
    out = {c: np.nan for c in columns}
    chunks = [p.strip() for p in text.split("|")]
    for part in chunks:
        if ":" not in part: continue
        k, v = part.split(":", 1)
        k = k.strip()
        if k in out: out[k] = v.strip()
    return out


# ==========================================
# SAVE HELPER
# ==========================================
def save_checkpoint(model, tokenizer, epoch: int, config: Dict, label: str = "epoch") -> None:
    """Unwrap Opacus/PEFT model and save LoRA adapter weights + tokenizer."""
    import os

    # Unwrap Opacus GradSampleModule wrapper
    base_model = model._module if hasattr(model, "_module") else model

    # Local save path
    local_path = os.path.join(config["local_checkpoint_dir"], f"{label}_{epoch}")
    os.makedirs(local_path, exist_ok=True)
    base_model.save_pretrained(local_path)
    tokenizer.save_pretrained(local_path)
    print(f"   💾 Checkpoint saved locally → {local_path}")

    # Optional: back up to Google Drive
    if config.get("save_to_drive", False):
        try:
            drive_path = os.path.join(config["drive_save_dir"], f"{label}_{epoch}")
            shutil.copytree(local_path, drive_path, dirs_exist_ok=True)
            print(f"   ☁️  Backed up to Drive → {drive_path}")
        except Exception as e:
            print(f"   ⚠️  Drive backup failed: {e}. Checkpoint is safe locally.")


# ==========================================
# DATASET
# ==========================================
class TabularTextDataset(Dataset):
    def __init__(self, row_texts, tokenizer, prompt, max_input_len, max_target_len):
        self.row_texts = row_texts
        self.tokenizer = tokenizer
        enc = tokenizer(prompt, truncation=True, max_length=max_input_len,
                        padding="max_length", return_tensors="pt")
        self.prompt_ids = enc["input_ids"].squeeze(0)
        self.prompt_mask = enc["attention_mask"].squeeze(0)
        self.max_target_len = max_target_len

    def __len__(self):
        return len(self.row_texts)

    def __getitem__(self, idx):
        tgt_tok = self.tokenizer(
            self.row_texts[idx], truncation=True,
            max_length=self.max_target_len, padding="max_length", return_tensors="pt"
        )
        labels = tgt_tok["input_ids"].squeeze(0)
        labels[labels == self.tokenizer.pad_token_id] = -100
        return {
            "input_ids": self.prompt_ids.clone(),
            "attention_mask": self.prompt_mask.clone(),
            "labels": labels,
        }


# ==========================================
# MAIN TRAINING FUNCTION
# ==========================================
def train_private_lora(config: Dict) -> None:
    print("=" * 60)
    print("🚀 INITIALIZING PRIVACY-PRESERVING SYNTHETIC DATA GENERATOR")
    print("=" * 60)

    set_seed(config["seed"])

    # ── Mount Drive early so we don't fail at save time ────────
    if config.get("save_to_drive", False):
        try:
            from google.colab import drive
            drive.mount("/content/drive")
            print("✅ Google Drive mounted.")
        except Exception as e:
            print(f"⚠️  Could not mount Drive: {e}. Will save locally only.")
            config["save_to_drive"] = False

    # 1. Device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"✅ Device: {device}")
    if device.type == "cuda":
        print(f"   GPU: {torch.cuda.get_device_name(0)}")
    else:
        print("   ⚠️  No GPU detected. Training will be slow.")

    # 2. Data
    print(f"\n📂 Loading data: {config['csv_path']}")
    try:
        real_df = pd.read_csv(config["csv_path"])
    except FileNotFoundError:
        raise FileNotFoundError(f"❌ File not found: {config['csv_path']}")

    columns = list(real_df.columns)
    print(f"   Rows: {len(real_df)} | Columns: {len(columns)}")
    row_texts = [serialize_row(real_df.iloc[i], columns) for i in range(len(real_df))]

    # 3. Model + LoRA
    print(f"\n🤖 Loading model: {config['model_name']}...")
    tokenizer = AutoTokenizer.from_pretrained(config["model_name"])
    model = AutoModelForSeq2SeqLM.from_pretrained(config["model_name"])
    lora_config = LoraConfig(
        r=8, lora_alpha=16, lora_dropout=0.05, bias="none",
        task_type=TaskType.SEQ_2_SEQ_LM, target_modules=["q", "v"]
    )
    model = get_peft_model(model, lora_config)
    model.to(device)
    model.train()
    print("   LoRA adapters attached.")

    # 4. DataLoader
    ds = TabularTextDataset(
        row_texts, tokenizer, config["prompt"],
        config["max_input_len"], config["max_target_len"]
    )
    base_loader = DataLoader(
        ds, batch_size=config["logical_batch_size"],
        shuffle=True, drop_last=True,
        pin_memory=(device.type == "cuda")
    )

    optimizer = torch.optim.AdamW(
        (p for p in model.parameters() if p.requires_grad), lr=config["lr"]
    )

    # 5. Privacy Engine
    sample_rate = config["logical_batch_size"] / len(ds)
    noise_multiplier = get_noise_multiplier(
        target_epsilon=config["target_epsilon"], target_delta=config["delta"],
        sample_rate=sample_rate, epochs=config["epochs"], accountant="rdp"
    )
    print(f"\n🔐 Privacy: Target ε={config['target_epsilon']} | Noise multiplier={noise_multiplier:.4f}")

    privacy_engine = PrivacyEngine(accountant="rdp")
    model, optimizer, private_loader = privacy_engine.make_private(
        module=model, optimizer=optimizer, data_loader=base_loader,
        noise_multiplier=noise_multiplier, max_grad_norm=config["max_grad_norm"],
        poisson_sampling=True
    )

    # 6. Training Loop
    print("\n🏋️  STARTING TRAINING")
    start_time = time.time()

    for epoch in range(1, config["epochs"] + 1):
        epoch_start = time.time()
        losses = []

        with BatchMemoryManager(
            data_loader=private_loader,
            max_physical_batch_size=config["physical_batch_size"],
            optimizer=optimizer
        ) as safe_loader:

            pbar = tqdm(safe_loader, desc=f"Epoch {epoch}/{config['epochs']}", leave=True)
            for batch in pbar:
                batch = {k: v.to(device) for k, v in batch.items()}
                optimizer.zero_grad()
                loss = model(**batch).loss
                loss.backward()
                optimizer.step()
                loss_val = loss.detach().item()
                losses.append(loss_val)
                pbar.set_postfix({"loss": f"{loss_val:.4f}"})

        avg_loss = np.mean(losses)
        eps_now = privacy_engine.get_epsilon(delta=config["delta"])
        epoch_dur = time.time() - epoch_start
        print(f"   ✅ Epoch {epoch} | Loss={avg_loss:.4f} | ε={eps_now:.3f} | Time={epoch_dur:.1f}s")
        print_gpu_status()

        # ── CHECKPOINT SAVE ──────────────────────────────────────
        if epoch % config["save_every_n_epochs"] == 0:
            save_checkpoint(model, tokenizer, epoch, config, label="epoch")

    total_time = time.time() - start_time
    print(f"\n🎉 Training Complete in {total_time / 60:.2f} minutes.")

    # ── FINAL SAVE ───────────────────────────────────────────────
    print("\n💾 Saving final model...")
    save_checkpoint(model, tokenizer, epoch="final", config=config, label="final")

    # 7. Generation
    print("\n🔮 GENERATING SYNTHETIC DATA")
    base_model = model._module if hasattr(model, "_module") else model
    base_model.eval()

    n_out = config["n_generate"] if config["n_generate"] is not None else len(real_df)
    generated_texts = []
    prompt_batch = [config["prompt"]] * config["physical_batch_size"]
    gen_pbar = tqdm(total=n_out, desc="Generating Rows")

    for start in range(0, n_out, config["physical_batch_size"]):
        bs = min(config["physical_batch_size"], n_out - start)
        toks = tokenizer(
            prompt_batch[:bs], return_tensors="pt", padding=True,
            truncation=True, max_length=config["max_input_len"]
        ).to(device)
        with torch.no_grad():
            gen_ids = base_model.generate(
                **toks, do_sample=True, temperature=config["temperature"],
                top_p=config["top_p"], max_new_tokens=config["max_new_tokens"]
            )
        texts = tokenizer.batch_decode(gen_ids, skip_special_tokens=True)
        generated_texts.extend(texts)
        gen_pbar.update(len(texts))

    gen_pbar.close()

    # 8. Save Output CSV
    print(f"\n💾 Processing {len(generated_texts)} generated rows...")
    synth_rows = [parse_row_text(t, columns) for t in generated_texts]
    synth_df = pd.DataFrame(synth_rows, columns=columns)
    for col in real_df.columns:
        if col in synth_df.columns and pd.api.types.is_numeric_dtype(real_df[col]):
            synth_df[col] = pd.to_numeric(synth_df[col], errors="coerce")

    synth_df.to_csv(config["out_csv"], index=False)
    print(f"✅ Synthetic data saved → {config['out_csv']}")
    print(f"   Original: {len(real_df)} rows | Synthetic: {len(synth_df)} rows")


# ==========================================
# ENTRY POINT
# ==========================================
if __name__ == "__main__":
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        gc.collect()

    train_private_lora(CONFIG)